#!/usr/bin/with-contenv bash
# shellcheck shell=bash

while IFS= read -r line; do
    pip3 install -U --no-cache-dir --find-links https://wheel-index.linuxserver.io/alpine-3.17/ -r \
        "${line}"
done < <(find /config/plugins -maxdepth 2 -name 'requirements.txt')
